module.exports = {
	desktop: {
		Clipboard: require("../openfl/desktop/Clipboard").default,
		// ClipboardFormats: require("../openfl/desktop/ClipboardFormats").default,
		ClipboardFormats: require("../openfl/desktop/_ClipboardFormats/ClipboardFormats_Impl_").default,
		// ClipboardTransferMode: require("../openfl/desktop/ClipboardTransferMode").default
		ClipboardTransferMode: require("../openfl/desktop/_ClipboardTransferMode/ClipboardTransferMode_Impl_").default
	},
	display: {
		Application: require("../openfl/display/Application").default,
		Bitmap: require("../openfl/display/Bitmap").default,
		BitmapData: require("../openfl/display/BitmapData").default,
		// BitmapDataChannel: require("../openfl/display/BitmapDataChannel").default,
		// BitmapDataChannel: require("../openfl/display/_BitmapDataChannel/BitmapDataChannel_Impl_").default,
		// BlendMode: require("../openfl/display/BlendMode").default,
		BlendMode: require("../openfl/display/_BlendMode/BlendMode_Impl_").default,
		// CapsStyle: require("../openfl/display/CapsStyle").default,
		CapsStyle: require("../openfl/display/_CapsStyle/CapsStyle_Impl_").default,
		// DirectRenderer: require("../openfl/display/DirectRenderer").default,
		DisplayObject: require("../openfl/display/DisplayObject").default,
		DisplayObjectContainer: require("../openfl/display/DisplayObjectContainer").default,
		// DOMSprite: require("../openfl/display/DOMSprite").default,
		FPS: require("../openfl/display/FPS").default,
		FrameLabel: require("../openfl/display/FrameLabel").default,
		// GradientType: require("../openfl/display/GradientType").default,
		GradientType: require("../openfl/display/_GradientType/GradientType_Impl_").default,
		Graphics: require("../openfl/display/Graphics").default,
		GraphicsBitmapFill: require("../openfl/display/GraphicsBitmapFill").default,
		GraphicsEndFill: require("../openfl/display/GraphicsEndFill").default,
		GraphicsGradientFill: require("../openfl/display/GraphicsGradientFill").default,
		GraphicsPath: require("../openfl/display/GraphicsPath").default,
		// GraphicsPathCommand: require("../openfl/display/GraphicsPathCommand").default,
		// GraphicsPathCommand: require("../openfl/display/_GraphicsPathCommand/GraphicsPathCommand_Impl_").default,
		// GraphicsPathWinding: require("../openfl/display/GraphicsPathWinding").default,
		GraphicsPathWinding: require("../openfl/display/_GraphicsPathWinding/GraphicsPathWinding_Impl_").default,
		GraphicsSolidFill: require("../openfl/display/GraphicsSolidFill").default,
		GraphicsStroke: require("../openfl/display/GraphicsStroke").default,
		IBitmapDrawable: require("../openfl/display/IBitmapDrawable").default,
		IGraphicsData: require("../openfl/display/IGraphicsData").default,
		IGraphicsFill: require("../openfl/display/IGraphicsFill").default,
		IGraphicsPath: require("../openfl/display/IGraphicsPath").default,
		IGraphicsStroke: require("../openfl/display/IGraphicsStroke").default,
		InteractiveObject: require("../openfl/display/InteractiveObject").default,
		// InterpolationMethod: require("../openfl/display/InterpolationMethod").default,
		InterpolationMethod: require("../openfl/display/_InterpolationMethod/InterpolationMethod_Impl_").default,
		// JointStyle: require("../openfl/display/JointStyle").default,
		JointStyle: require("../openfl/display/_JointStyle/JointStyle_Impl_").default,
		JPEGEncoderOptions: require("../openfl/display/JPEGEncoderOptions").default,
		// LineScaleMode: require("../openfl/display/LineScaleMode").default,
		LineScaleMode: require("../openfl/display/_LineScaleMode/LineScaleMode_Impl_").default,
		Loader: require("../openfl/display/Loader").default,
		LoaderInfo: require("../openfl/display/LoaderInfo").default,
		MovieClip: require("../openfl/display/MovieClip").default,
		// OpenGLView: require("../openfl/display/OpenGLView").default,
		// PixelSnapping: require("../openfl/display/PixelSnapping").default,
		PixelSnapping: require("../openfl/display/_PixelSnapping/PixelSnapping_Impl_").default,
		PNGEncoderOptions: require("../openfl/display/PNGEncoderOptions").default,
		Preloader: require("../openfl/display/Preloader").default,
		Shader: require("../openfl/display/Shader").default,
		ShaderData: require("../openfl/display/ShaderData").default,
		ShaderInput: require("../openfl/display/ShaderInput").default,
		ShaderJob: require("../openfl/display/ShaderJob").default,
		ShaderParameter: require("../openfl/display/ShaderParameter").default,
		// ShaderParameterType: require("../openfl/display/ShaderParameterType").default,
		ShaderParameterType: require("../openfl/display/_ShaderParameterType/ShaderParameterType_Impl_").default,
		// ShaderPrecision: require("../openfl/display/ShaderPrecision").default,
		// ShaderPrecision: require("../openfl/display/ShaderPrecision").default,
		Shape: require("../openfl/display/Shape").default,
		SimpleButton: require("../openfl/display/SimpleButton").default,
		// SpreadMethod: require("../openfl/display/SpreadMethod").default,
		SpreadMethod: require("../openfl/display/_SpreadMethod/SpreadMethod_Impl_").default,
		Sprite: require("../openfl/display/Sprite").default,
		Stage: require("../openfl/display/Stage").default,
		Stage3D: require("../openfl/display/Stage3D").default,
		// StageAlign: require("../openfl/display/StageAlign").default,
		// StageAlign: require("../openfl/display/StageAlign").default,
		// StageDisplayState: require("../openfl/display/StageDisplayState").default,
		StageDisplayState: require("../openfl/display/_StageDisplayState/StageDisplayState_Impl_").default,
		// StageQuality: require("../openfl/display/StageQuality").default,
		StageQuality: require("../openfl/display/_StageQuality/StageQuality_Impl_").default,
		// StageScaleMode: require("../openfl/display/StageScaleMode").default,
		StageScaleMode: require("../openfl/display/_StageScaleMode/StageScaleMode_Impl_").default,
		Tile: require("../openfl/display/Tile").default,
		TileArray: require("../openfl/display/TileArray").default,
		Tilemap: require("../openfl/display/Tilemap").default,
		Tileset: require("../openfl/display/Tileset").default,
		// TriangleCulling: require("../openfl/display/TriangleCulling").default,
		TriangleCulling: require("../openfl/display/_TriangleCulling/TriangleCulling_Impl_").default,
		Window: require("../openfl/display/Window").default
	},
	display3D: {
		textures: {
			CubeTexture: require("../openfl/display3D/textures/CubeTexture").default,
			RectangleTexture: require("../openfl/display3D/textures/RectangleTexture").default,
			Texture: require("../openfl/display3D/textures/Texture").default,
			TextureBase: require("../openfl/display3D/textures/TextureBase").default,
		},
		Context3D: require("../openfl/display3D/Context3D").default,
		// Context3DBlendFactor: require("../openfl/display3D/Context3DBlendFactor").default,
		Context3DBlendFactor: require("../openfl/display3D/_Context3DBlendFactor/Context3DBlendFactor_Impl_").default,
		// Context3DBufferUsage: require("../openfl/display3D/Context3DBufferUsage").default,
		Context3DBufferUsage: require("../openfl/display3D/_Context3DBufferUsage/Context3DBufferUsage_Impl_").default,
		// Context3DClearMask: require("../openfl/display3D/Context3DClearMask").default,
		// Context3DClearMask: require("../openfl/display3D/_Context3DClearMask/Context3DClearMask_Impl_").default,
		// Context3DCompareMode: require("../openfl/display3D/Context3DCompareMode").default,
		Context3DCompareMode: require("../openfl/display3D/_Context3DCompareMode/Context3DCompareMode_Impl_").default,
		// Context3DMipFilter: require("../openfl/display3D/Context3DMipFilter").default,
		Context3DMipFilter: require("../openfl/display3D/_Context3DMipFilter/Context3DMipFilter_Impl_").default,
		// Context3DProfile: require("../openfl/display3D/Context3DProfile").default,
		Context3DProfile: require("../openfl/display3D/_Context3DProfile/Context3DProfile_Impl_").default,
		// Context3DProgramType: require("../openfl/display3D/Context3DProgramType").default,
		Context3DProgramType: require("../openfl/display3D/_Context3DProgramType/Context3DProgramType_Impl_").default,
		// Context3DRenderMode: require("../openfl/display3D/Context3DRenderMode").default,
		Context3DRenderMode: require("../openfl/display3D/_Context3DRenderMode/Context3DRenderMode_Impl_").default,
		// Context3DStencilAction: require("../openfl/display3D/Context3DStencilAction").default,
		Context3DStencilAction: require("../openfl/display3D/_Context3DStencilAction/Context3DStencilAction_Impl_").default,
		// Context3DTextureFilter: require("../openfl/display3D/Context3DTextureFilter").default,
		Context3DTextureFilter: require("../openfl/display3D/_Context3DTextureFilter/Context3DTextureFilter_Impl_").default,
		// Context3DTextureFormat: require("../openfl/display3D/Context3DTextureFormat").default,
		Context3DTextureFormat: require("../openfl/display3D/_Context3DTextureFormat/Context3DTextureFormat_Impl_").default,
		// Context3DTriangleFace: require("../openfl/display3D/Context3DTriangleFace").default,
		Context3DTriangleFace: require("../openfl/display3D/_Context3DTriangleFace/Context3DTriangleFace_Impl_").default,
		// Context3DVertexBufferFormat: require("../openfl/display3D/Context3DVertexBufferFormat").default,
		Context3DVertexBufferFormat: require("../openfl/display3D/_Context3DVertexBufferFormat/Context3DVertexBufferFormat_Impl_").default,
		// Context3DWrapMode: require("../openfl/display3D/Context3DWrapMode").default,
		Context3DWrapMode: require("../openfl/display3D/_Context3DWrapMode/Context3DWrapMode_Impl_").default,
		// IndexBuffer3D: require("../openfl/display3D/IndexBuffer3D").default,
		Program3D: require("../openfl/display3D/Program3D").default,
		VertexBuffer3D: require("../openfl/display3D/VertexBuffer3D").default,
	},
	errors: {
		ArgumentError: require("../openfl/errors/ArgumentError").default,
		EOFError: require("../openfl/errors/EOFError").default,
		Error: require("../openfl/errors/Error").default,
		IllegalOperationError: require("../openfl/errors/IllegalOperationError").default,
		IOError: require("../openfl/errors/IOError").default,
		RangeError: require("../openfl/errors/RangeError").default,
		SecurityError: require("../openfl/errors/SecurityError").default,
		TypeError: require("../openfl/errors/TypeError").default,
	},
	events: {
		AccelerometerEvent: require("../openfl/events/AccelerometerEvent").default,
		ActivityEvent: require("../openfl/events/ActivityEvent").default,
		AsyncErrorEvent: require("../openfl/events/AsyncErrorEvent").default,
		DataEvent: require("../openfl/events/DataEvent").default,
		ErrorEvent: require("../openfl/events/ErrorEvent").default,
		Event: require("../openfl/events/Event").default,
		EventDispatcher: require("../openfl/events/EventDispatcher").default,
		// EventPhase: require("../openfl/events/EventPhase").default,
		// EventPhase: require("../openfl/events/_EventPhase/EventPhase_Impl_").default,
		FocusEvent: require("../openfl/events/FocusEvent").default,
		FullScreenEvent: require("../openfl/events/FullScreenEvent").default,
		GameInputEvent: require("../openfl/events/GameInputEvent").default,
		HTTPStatusEvent: require("../openfl/events/HTTPStatusEvent").default,
		IEventDispatcher: require("../openfl/events/IEventDispatcher").default,
		IOErrorEvent: require("../openfl/events/IOErrorEvent").default,
		KeyboardEvent: require("../openfl/events/KeyboardEvent").default,
		MouseEvent: require("../openfl/events/MouseEvent").default,
		NetStatusEvent: require("../openfl/events/NetStatusEvent").default,
		ProgressEvent: require("../openfl/events/ProgressEvent").default,
		SampleDataEvent: require("../openfl/events/SampleDataEvent").default,
		SecurityErrorEvent: require("../openfl/events/SecurityErrorEvent").default,
		TextEvent: require("../openfl/events/TextEvent").default,
		TimerEvent: require("../openfl/events/TimerEvent").default,
		TouchEvent: require("../openfl/events/TouchEvent").default,
		UncaughtErrorEvent: require("../openfl/events/UncaughtErrorEvent").default,
		UncaughtErrorEvents: require("../openfl/events/UncaughtErrorEvents").default,
	},
	external: {
		ExternalInterface: require("../openfl/external/ExternalInterface").default,
	},
	filters: {
		BitmapFilter: require("../openfl/filters/BitmapFilter").default,
		// BitmapFilterQuality: require("../openfl/filters/BitmapFilterQuality").default,
		// BitmapFilterQuality: require("../openfl/filters/_BitmapFilterQuality/BitmapFilterQuality_Impl_").default,
		// BitmapFilterType: require("../openfl/filters/BitmapFilterType").default,
		BitmapFilterType: require("../openfl/filters/_BitmapFilterType/BitmapFilterType_Impl_").default,
		BlurFilter: require("../openfl/filters/BlurFilter").default,
		ColorMatrixFilter: require("../openfl/filters/ColorMatrixFilter").default,
		// ConvolutionFilter: require("../openfl/filters/ConvolutionFilter").default,
		DropShadowFilter: require("../openfl/filters/DropShadowFilter").default,
		GlowFilter: require("../openfl/filters/GlowFilter").default,
	},
	geom: {
		ColorTransform: require("../openfl/geom/ColorTransform").default,
		Matrix: require("../openfl/geom/Matrix").default,
		Matrix3D: require("../openfl/geom/Matrix3D").default,
		// Orientation3D: require("../openfl/geom/Orientation3D").default,
		Orientation3D: require("../openfl/geom/_Orientation3D/Orientation3D_Impl_").default,
		PerspectiveProjection: require("../openfl/geom/PerspectiveProjection").default,
		Point: require("../openfl/geom/Point").default,
		Rectangle: require("../openfl/geom/Rectangle").default,
		Transform: require("../openfl/geom/Transform").default,
		Utils3D: require("../openfl/geom/Utils3D").default,
		Vector3D: require("../openfl/geom/Vector3D").default,
	},
	media: {
		ID3Info: require("../openfl/media/ID3Info").default,
		Sound: require("../openfl/media/Sound").default,
		SoundChannel: require("../openfl/media/SoundChannel").default,
		SoundLoaderContext: require("../openfl/media/SoundLoaderContext").default,
		SoundTransform: require("../openfl/media/SoundTransform").default,
		Video: require("../openfl/media/Video").default,
	},
	net: {
		FileFilter	: require("../openfl/net/FileFilter").default,
		FileReference: require("../openfl/net/FileReference").default,
		FileReferenceList: require("../openfl/net/FileReferenceList").default,
		NetConnection: require("../openfl/net/NetConnection").default,
		NetStream: require("../openfl/net/NetStream").default,
		SharedObject: require("../openfl/net/SharedObject").default,
		// SharedObjectFlushStatus: require("../openfl/net/SharedObjectFlushStatus").default,
		SharedObjectFlushStatus: require("../openfl/net/_SharedObjectFlushStatus/SharedObjectFlushStatus_Impl_").default,
		Socket: require("../openfl/net/Socket").default,
		URLLoader: require("../openfl/net/URLLoader").default,
		// URLLoaderDataFormat: require("../openfl/net/URLLoaderDataFormat").default,
		URLLoaderDataFormat: require("../openfl/net/_URLLoaderDataFormat/URLLoaderDataFormat_Impl_").default,
		URLRequest	: require("../openfl/net/URLRequest").default,
		URLRequestDefaults: require("../openfl/net/URLRequestDefaults").default,
		URLRequestHeader: require("../openfl/net/URLRequestHeader").default,
		// URLRequestMethod: require("../openfl/net/URLRequestMethod").default,
		// URLRequestMethod: require("../openfl/net/_URLRequestMethod/URLRequestMethod_Impl_").default,
		URLStream: require("../openfl/net/URLStream").default,
		URLVariables: require("../openfl/net/URLVariables").default,
		XMLSocket: require("../openfl/net/XMLSocket").default,
	},
	profiler: {
		Telemetry: require("../openfl/profiler/Telemetry").default,
	},
	sensors: {
		Accelerometer: require("../openfl/sensors/Accelerometer").default,
	},
	system: {
		ApplicationDomain: require("../openfl/system/ApplicationDomain").default,
		Capabilities: require("../openfl/system/Capabilities").default,
		LoaderContext: require("../openfl/system/LoaderContext").default,
		Security: require("../openfl/system/Security").default,
		SecurityDomain: require("../openfl/system/SecurityDomain").default,
		System: require("../openfl/system/System").default,
		// TouchscreenType: require("../openfl/system/TouchscreenType").default,
		TouchscreenType: require("../openfl/system/_TouchscreenType/TouchscreenType_Impl_").default,
	},
	text: {
		// AntiAliasType: require("../openfl/text/AntiAliasType").default,
		AntiAliasType: require("../openfl/text/_AntiAliasType/AntiAliasType_Impl_").default,
		Font: require("../openfl/text/Font").default,
		// FontStyle: require("../openfl/text/FontStyle").default,
		FontStyle: require("../openfl/text/_FontStyle/FontStyle_Impl_").default,
		// FontType: require("../openfl/text/FontType").default,
		FontType: require("../openfl/text/_FontType/FontType_Impl_").default,
		// GridFitType: require("../openfl/text/GridFitType").default,
		GridFitType: require("../openfl/text/_GridFitType/GridFitType_Impl_").default,
		TextField: require("../openfl/text/TextField").default,
		// TextFieldAutoSize: require("../openfl/text/TextFieldAutoSize").default,
		TextFieldAutoSize: require("../openfl/text/_TextFieldAutoSize/TextFieldAutoSize_Impl_").default,
		// TextFieldType: require("../openfl/text/TextFieldType").default,
		TextFieldType: require("../openfl/text/_TextFieldType/TextFieldType_Impl_").default,
		TextFormat: require("../openfl/text/TextFormat").default,
		// TextFormatAlign: require("../openfl/text/TextFormatAlign").default,
		TextFormatAlign: require("../openfl/text/_TextFormatAlign/TextFormatAlign_Impl_").default,
		TextLineMetrics: require("../openfl/text/TextLineMetrics").default,
	},
	ui: {
		GameInput: require("../openfl/ui/GameInput").default,
		GameInputControl: require("../openfl/ui/GameInputControl").default,
		GameInputDevice: require("../openfl/ui/GameInputDevice").default,
		Keyboard: require("../openfl/ui/Keyboard").default,
		// KeyLocation: require("../openfl/ui/KeyLocation").default,
		// KeyLocation: require("../openfl/ui/_KeyLocation/KeyLocation_Impl_").default,
		Mouse: require("../openfl/ui/Mouse").default,
		// MouseCursor: require("../openfl/ui/MouseCursor").default,
		MouseCursor: require("../openfl/ui/_MouseCursor/MouseCursor_Impl_").default,
		Multitouch: require("../openfl/ui/Multitouch").default,
		// MultitouchInputMode: require("../openfl/ui/MultitouchInputMode").default,
		MultitouchInputMode: require("../openfl/ui/_MultitouchInputMode/MultitouchInputMode_Impl_").default,
	},
	utils: {
		AGALMiniAssembler: require("../openfl/utils/AGALMiniAssembler").default,
		// ByteArray: require("../openfl/utils/ByteArray").default,
		ByteArray: require("../openfl/utils/ByteArrayData").default,
		//CompressionAlgorithm: require("../openfl/utils/CompressionAlgorithm").default,
		CompressionAlgorithm: require("../openfl/utils/_CompressionAlgorithm/CompressionAlgorithm_Impl_").default,
		//Dictionary: require("../openfl/utils/Dictionary").default,
		Dictionary: require("../openfl/utils/_Dictionary/Dictionary_Impl_").default,
		//Endian: require("../openfl/utils/Endian").default,
		Endian: require("../openfl/utils/_Endian/Endian_Impl_").default,
		IDataInput: require("../openfl/utils/IDataInput").default,
		IDataOutput: require("../openfl/utils/IDataOutput").default,
		// Object: require("../openfl/utils/Object").default,
		Object: require("../openfl/utils/_Object/Object_Impl_").default,
		Timer: require("../openfl/utils/Timer").default,
	},
	// Assets: require("../openfl/Assets").default,
	Lib: require("../openfl/Lib").default,
	Memory: require("../openfl/Memory").default,
	// Vector: require("../openfl/Vector").default,
}

module.exports.Assets = module.exports.utils.Assets;